name: Deploy Astro site to Pages

on:
  push:
    branches:
    - master # Cambia "master" por la rama principal de tu repositorio si es necesario
  workflow_dispatch:


permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    # Clona el repositorio
    - name: Checkout code
      uses: actions/checkout@v4

    # Configura Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    # Instala dependencias
    - name: Install dependencies
      run: npm ci

    # Construye el proyecto con Astro
    - name: Build the project
      run: npm run build

    # Despliega el directorio "dist" en GitHub Pages
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      with:
        path: dist
